language: java
jdk: oraclejdk8

install: true

before_script:
  - openssl aes-256-cbc -K $encrypted_65aa329e7553_key -iv $encrypted_65aa329e7553_iv -in gradle.properties.enc -out gradle.properties -d

script:
  - make build

deploy:
  provider: script
  script: make travis-deploy
  on:
    tags: true
